name: WorldTp
version: 0.25
main: me.Batsed.WorldTp.WorldTp
author: Batsed
website: http://Batsed.de
commands:
     creativ:
          description: Bringt dich in eine andere Welt
          usage: /<command>
     setspawnpoint:
          description: Setzt den Spawnpoint in der Welt
          usage: /<command>
     leave:
          description: Um aus der Welt raus zu kommen
          usage: /<command>
     worldtp:
          description: Um Hilfe zu bekommen
          usage: /<command>
     wt:
          description: Um Hilfe zu bekommen
          usage: /<command>