name: WorldTp
version: 0.5
main: me.Batsed.WorldTp.WorldTp
author: Batsed
website: http://Batsed.de
commands:
     wt:
          description: You go to the spawn point you set
          usage: /<command> <name>
     setspawnpoint:
          description: Sets the spawn point you reach with /creative
          usage: /<command> <name>
     leave:
          description: You leave the creative world
          usage: /<command>
     worldtp:
          description: Read the help for WorldTP
          usage: /<command>